<x-layout>
    <x-container>
        <x-navbar />
    </x-container>

    <x-article>
        <x-slot:title>Privacy <span class="snapdb-underline underline-thick">Policy</span></x-slot:title>
        <x-slot:meta>Last updated Jan 15, 2025.</x-slot:meta>
        <x-slot:body>
            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Definitions</h2>

                <ul class="list-disc pl-6">
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "SnapDB", "Us" or "Our" in this Agreement) refers to SnapDB, located in the Netherlands.</li>
                    <li><strong>Account</strong> means a unique account or license created for You to access our Service or parts of our Service.</li>
                    <li><strong>Website</strong> refers to SnapDB, accessible from {{ url('/') }}.</li>
                    <li><strong>Service</strong> refers to the website and or any other software, downloads, apps offered by the Company.</li>
                    <li><strong>Country</strong> refers to: the Netherlands.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                </ul>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Foreword</h2>

                <p>
                    We are very delighted that you have shown interest in our service. Data protection
                    is of a particularly high priority for the management of the SnapDB. The use of the services
                    of SnapDB website is possible without any indication of personal data; however, if a data subject
                    wants to use special services via our website or app, processing of personal data could
                    become necessary. If the processing of personal data is necessary and there is no statutory
                    basis for such processing, we generally obtain consent from the data subject.
                </p>

                <p>
                    The processing of personal data, such as the name, address, e-mail address,
                    or telephone number of a data subject shall always be in line with the
                    General Data Protection Regulation (GDPR), and in accordance with the country-specific
                    data protection regulations applicable to SnapDB. By means of this data protection declaration,
                    our enterprise would like to inform the general public of the nature, scope, and purpose
                    of the personal data we collect, use and process. Furthermore, data subjects are informed,
                    by means of this data protection declaration, of the rights to which they are entitled.
                </p>

                <p>
                    As the controller, SnapDB has implemented numerous technical and organizational
                    measures to ensure the most complete protection of personal data processed through
                    the SnapDB service(s). However, Internet-based data transmissions may in principle have
                    security gaps, so absolute protection may not be guaranteed. For this reason, every
                    data subject is free to transfer personal data to us via alternative means,
                    e.g. by telephone.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Information of the controller</h2>

                <p>
                    Controller for the purposes of the General Data Protection Regulation (GDPR),
                    other data protection laws applicable in Member states of the European Union and
                    other provisions related to data protection is:
                </p>
                <p>
                    <strong>SnapDB</strong>, located in <strong>the Netherlands</strong>.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Cookies</h2>

                <p>
                    The Internet pages of the SnapDB use cookies. Cookies are text files that
                    are stored in a computer system via an Internet browser.
                </p>

                <p>
                    Many Internet sites and servers use cookies. Many cookies contain a
                    so-called cookie ID. A cookie ID is a unique identifier of the cookie.
                    It consists of a character string through which Internet pages and servers
                    can be assigned to the specific Internet browser in which the cookie was stored.
                    This allows visited Internet sites and servers to differentiate the individual browser
                    of the dats subject from other Internet browsers that contain other cookies. A
                    specific Internet browser can be recognized and identified using the unique cookie ID.
                </p>

                <p>
                    Through the use of cookies, SnapDB can provide the users of this website
                    with more user-friendly services that would not be possible without the
                    cookie setting.
                </p>

                <p>
                    By means of a cookie, the information and offers on our website can be
                    optimized with the user in mind. Cookies allow us, as previously mentioned,
                    to recognize our website users. The purpose of this recognition is to make
                    it easier for users to utilize our website. The website user that uses cookies,
                    e.g. does not have to enter access data each time the website is accessed, because
                    this is taken over by the website, and the cookie is thus stored on the user's computer system.
                    Another example is the cookie of a shopping cart in an online shop. The online store
                    remembers the articles that a customer has placed in the virtual shopping cart via a cookie.
                </p>

                <p>
                    The data subject may, at any time, prevent the setting of cookies through
                    our website by means of a corresponding setting of the Internet browser
                    used, and may thus permanently deny the setting of cookies. Furthermore,
                    already set cookies may be deleted at any time via an Internet browser or
                    other software programs. This is possible in all popular Internet browsers.
                    If the data subject deactivates the setting of cookies in the Internet browser
                    used, not all functions of our website may be entirely usable.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Use of your personal data</h2>

                <p>
                    SnapDB may use Personal Data for the following purposes:
                </p>

                <ul class="list-disc pl-6">
                    <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                    <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                    <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                    <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                    <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                    To manage Your requests: To attend and manage Your requests to Us.
                </ul>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Sharing of your personal data</h2>

                <p>
                    SnapDB may share Personal Data for the following purposes:
                </p>

                <ul class="list-disc pl-6">
                    <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                    <li>For Business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
                    <li>With Business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                    <li>With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
                </ul>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Retention of your personal data</h2>

                <p>
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>

                <p>
                    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Transfer of your personal data</h2>

                <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>

                <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

                <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Disclosure of Your Personal Data</h2>

                <p>
                    <strong class="block">Business Transactions</strong>
                    If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                </p>

                <p>
                    <strong class="block">Law enforcement</strong>
                    Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </p>

                <p>
                    <strong class="block">Other legal requirements</strong>
                    The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                </p>

                <ul class="list-disc pl-6">
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                </ul>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Security of Your Personal Data</h2>

                <p>
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Children's Privacy</h2>

                <p>
                    Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.
                </p>

                <p>
                    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Links to Other Sites</h2>

                <p>
                    Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                </p>

                <p>
                    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Changes to this Privacy Policy</h2>

                <p>
                    We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                </p>

                <p>
                    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                </p>

                <p>
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
            </section>

            <section class="flex flex-col gap-4 mb-4">
                <h2 class="text-xl font-bold">Contact Us</h2>
                <p>
                    In order to resolve a complaint regarding SnapDB or to receive further information regarding use of the Site, please get in touch on our <a href="{{ route('contact') }}" class="link">contact page</a>.
                </p>
            </section>
        </x-slot:body>
    </x-article>
</x-layout>
